### ISSUE TITLE
Cannot find name 'TransformStream' after updating to v5.2.0

### ISSUE THREAD

**Issue by Julien-Marcou** [socketio/socket.io#5064]
Since I updated `socket.io` from the `v4.7.1` to the `v4.7.2` (and so `engine.io-parser` from the `v5.1.0` to the `v5.2.1`), I'm getting the following errors while building my projects:

```sh
node_modules/engine.io-parser/build/cjs/index.d.ts:6:54 - error TS2304: Cannot find name 'TransformStream'.
6 export declare function createPacketEncoderStream(): TransformStream<Packet, any>;
                                                       ~~~~~~~~~~~~~~~
node_modules/engine.io-parser/build/cjs/index.d.ts:7:96 - error TS2304: Cannot find name 'TransformStream'.
7 export declare function createPacketDecoderStream(maxPayload: number, binaryType: BinaryType): TransformStream<Uint8Array, any>;
                                                                                                 ~~~~~~~~~~~~~~~

Found 2 errors in the same file, starting at: node_modules/engine.io-parser/build/cjs/index.d.ts:6
```

Funnily, I'm only getting this error when compiling using `tsc` but not when compiling using `esbuild`.

`npx tsc` -> error
`npx esbuild src/index.ts --platform=node` -> ok

Here is my `tsconfig.json`:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist",
    "strict": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node16",
    "importHelpers": true,
    "target": "es2022",
    "module": "node16",
    "lib": [
      "es2022"
    ]
  },
  "include": [
    "src/**/*.ts"
  ]
}
```

Reading nodejs's documentation, when using `TransformStream`, it looks like they are importing it with

```ts
import { TransformStream } from 'node:stream/web';
```

which is not the case for `engine.io-parser`, so maybe that's the problem.

**Comment by darrachequesne** [comment]
@Sekkmer this should be fixed by https://github.com/socketio/socket.io/commit/f9cb983ab7050c0a1630cfc97eb30f2dd807186b, included in `engine.io-parser@5.2.3`. Could you please check?

**Comment by Sekkmer** [comment]
> @Sekkmer this should be fixed by [f9cb983](https://github.com/socketio/socket.io/commit/f9cb983ab7050c0a1630cfc97eb30f2dd807186b), included in `engine.io-parser@5.2.3`. Could you please check?

@darrachequesne I tested it, and it works :)

**Comment by darrachequesne** [comment]
@Sekkmer awesome, thanks of the update :+1: I think this can be closed now.
