### ISSUE TITLE
Type definitions are invalid in SocketIO 3 - Property 'emit' in type 'Namespace'

### ISSUE THREAD

**Issue by myfatemi04** [socketio/socket.io#3694]
I tried compiling with TSC after updating SocketIO to 3.0.0 and received this error.

```
node_modules/socket.io/dist/index.d.ts:2:8 - error TS1192: Module '"http"' has no default export.

2 import http from "http";
         ~~~~

node_modules/socket.io/dist/namespace.d.ts:89:5 - error TS2416: Property 'emit' in type 'Namespace' is not assignable to the same property in base type 'EventEmitter'.
  Type '(ev: string, ...args: any[]) => Namespace' is not assignable to type '(event: string | symbol, ...args: any[]) => boolean'.
    Type 'Namespace' is not assignable to type 'boolean'.

89     emit(ev: string, ...args: any[]): Namespace;
       ~~~~

node_modules/socket.io/dist/socket.d.ts:84:5 - error TS2416: Property 'emit' in type 'Socket' is not assignable to the same property in base type 'EventEmitter'.
  Type '(ev: string, ...args: any[]) => this' is not assignable to type '(event: string | symbol, ...args: any[]) => boolean'.
    Type 'this' is not assignable to type 'boolean'.
      Type 'Socket' is not assignable to type 'boolean'.

84     emit(ev: string, ...args: any[]): this;
```

**Comment by darrachequesne** [comment]
Hi! Could you please check with version `3.0.1`? It should be fixed by https://github.com/socketio/socket.io/commit/50671d984a81535a6a15c704546ca7465e2ea295.

**Comment by myfatemi04** [comment]
That worked! Thank you
